### ISSUE TITLE
W1 Test CRUD functions

### ISSUE THREAD

**Issue by AdamDomafoldi** [codingmentor/film-es-sorozatnyilvantarto#11]
Megbeszélés alapján ezek lehetnek .sh szkriptek vagy egy dokumentáció az endpointokról és azokat Postmannal teszteljük.

**Comment by adam-marton** [comment]
A DELETE-re dobott 400 Bad Request-re solution:
http://blogs.steeplesoft.com/posts/2012/glassfish-3-1-2-and-rest-security.html

Ez postman alatt annyit jelent, hogy kell egy Headert megadni, aminek a kulcsa: X-Requested-By, értéke bármi lehet.

**Comment by AdamDomafoldi** [comment]
Figyelni fogok rá majd. Köszi az infót!
