### ISSUE TITLE
W1 Create scripts for server config

### ISSUE THREAD

**Issue by adam-marton** [codingmentor/film-es-sorozatnyilvantarto#13]
Létre kell hozni szkriptfájl(oka)t, amely(ek) segítségével be lehet konfigurálni a szervert az alkalmazásunkhoz.
-connection pool létrehozása
-jdbc resource létrehozása

A feladatkiírás idevágó része:

> Alkalmazásszerver
> A projekthez használt alkalmazásszerver teljes felkonfigurálására legyen lehetőség scriptekből, ezek a scriptek legyenek megtalálhatók a repository-ban.

**Comment by labanczjeno** [comment]
következőképpen haszbáljátok majd a scripteket:
1. másoljátok be a scripteket a C:\GlassFish\bin -be (vagy amilyen útvonalon telepítettétek a GlassFisht)
2. a createDomainMoviesAndSeriesDB-t futtassátok először
3. a postgresql-9.4.1212.jar -otokat másoljátok be a C:\GlassFish\glassfish\domains\MoviesAndSeriesDB-domain\lib -be (vagy szintén az egyéni útvonalon)
4. startDomainMoviesAndSeriesDB futtatása
5. createConnectionPoolMoviesAndSeriesDB futtatása
6. createResourceMoviesAndSeriesDB futtatása
7. stopDomainMoviesAndSeriesDB futtatása

**Comment by labanczjeno** [comment]
pusholtam
