### ISSUE TITLE
W2 Fix database prototype

### ISSUE THREAD

**Issue by adam-marton** [codingmentor/film-es-sorozatnyilvantarto#21]
- táblák nevei ne legyenek többesszámban
- rendezők és sorozatok között több-több kapcsolat
- tábla készítése a role-okhoz

**Comment by adam-marton** [comment]
![moviedb](https://cloud.githubusercontent.com/assets/24194198/23223735/2533059e-f92c-11e6-89a9-ecf27f48e915.png)

**Comment by AdamDomafoldi** [comment]
Szerintem a szombati megbeszélésen elvégzett javítások el lettek végezve. Én nem látok más hibát most.

**Comment by adam-marton** [comment]
a jaas példánál, amikor glassfish admin oldalán állítottuk be a jaas-t, ott csak user és user_group table-t kellett beállítani, nem?

**Comment by AdamDomafoldi** [comment]
Igen, meg is néztem. Szóval a kérdésem így tárgytalan.
