### ISSUE TITLE
W3 Wrap server config scripts into one file

### ISSUE THREAD

**Issue by adam-marton** [codingmentor/film-es-sorozatnyilvantarto#37]
A szerver konfigurálásához használt szkripteket be kell csomagolni egy fájlba, hogy ne kelljen ~10 fájlt külön futtatni.

**Comment by AdamDomafoldi** [comment]
Config egy runMe .bat szkript segítségével fut. A config futtatásához az összes file-t a glassfish bin mappájába kell másolni. A runMe futtatása közben bekonfigol mindent, bemásolja a postgre.jar-t a megfelelő helyre hogy az adatbázis működjön, majd kitörli a bemásolt szkripteket, hogy azok ne legyenek ott feleslegesen.
