### ISSUE TITLE
W1 Design database prototype - DÁ

### ISSUE THREAD

**Issue by AdamDomafoldi** [codingmentor/film-es-sorozatnyilvantarto#6]
Készítettem egy béta adatbázis tervet. Ahol nincs elsődleges kulcs, ott összetett kulcs lesz. Én a lehető legkevesebb kapcsolótáblával dolgoznék. 

[Adatbázisterv](https://domafoldi.hu/up/db.png)

**Comment by AdamDomafoldi** [comment]
Készítettem egy béta adatbázis tervet. Ahol nincs elsődleges kulcs, ott összetett kulcs lesz. Én a lehető legkevesebb kapcsolótáblával dolgoznék. 

[Adatbázisterv](https://domafoldi.hu/up/db.png)

**Comment by adam-marton** [comment]
![image](https://cloud.githubusercontent.com/assets/24194198/22919222/dac599de-f28e-11e6-8123-d298a8e26991.png)

Közös megegyezés alapján így alakult a végső terv.

**Comment by adam-marton** [comment]
![moviedb](https://cloud.githubusercontent.com/assets/24194198/23258398/6403e6d4-f9c8-11e6-83e7-eafcbadd1079.png)

A 21-es Issue alapján megváltozott terv.
https://github.com/codingmentor/film-es-sorozatnyilvantarto/issues/21
