### ISSUE TITLE
W1 Create @Entities

### ISSUE THREAD

**Issue by AdamDomafoldi** [codingmentor/film-es-sorozatnyilvantarto#7]
Az elfogadott adatbázisterv alapján elkészíteni a Java entitásokat.

**Comment by labanczjeno** [comment]
[movierepository.zip](https://github.com/codingmentor/film-es-sorozatnyilvantarto/files/774595/movierepository.zip)

**Comment by labanczjeno** [comment]
![nevtelen](https://cloud.githubusercontent.com/assets/23979692/22936785/d6d18a0c-f2d6-11e6-8c48-010ee55e7648.jpg)
![nevtelen2](https://cloud.githubusercontent.com/assets/23979692/22936795/da33613e-f2d6-11e6-91f8-61f68a13901d.jpg)
![nevtelen3](https://cloud.githubusercontent.com/assets/23979692/22936799/dda7a26c-f2d6-11e6-95a7-3574a03a3bb1.jpg)
